/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uvnaloga1;

import javax.swing.*;

/**
 *
 * @author Tomaz Lunder
 */
public class MainJFrame extends javax.swing.JFrame {
    
    final String IZHOD_PRE = "Vrstica za sporočila: ";

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        StatusLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RadioOdstraniPrvega = new javax.swing.JRadioButton();
        RadioDodaj = new javax.swing.JRadioButton();
        RadioOdstraniIzbranega = new javax.swing.JRadioButton();
        TextVnos = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        BtnIzvedi = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        CheckDvojniki = new javax.swing.JCheckBox();
        izhodLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setMnemonic('T');
        jButton1.setText("Izbire1 T");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setMnemonic('O');
        jButton2.setText("Izbire1 O");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setMnemonic('M');
        jButton3.setText("Izbire1 M");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setMnemonic('A');
        jButton4.setText("Izbire1 A");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setMnemonic('\u017d');
        jButton5.setText("Izbire1 Ž");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setMnemonic('L');
        jButton6.setText("Izbire2 L");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setMnemonic('U');
        jButton7.setText("Izbire2 U");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton8.setMnemonic('N');
        jButton8.setText("Izbire2 N");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton9.setMnemonic('D');
        jButton9.setText("Izbire2 D");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton9);

        jButton10.setMnemonic('E');
        jButton10.setText("Izbire2 E");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton10);

        jButton11.setMnemonic('R');
        jButton11.setText("Izbire2 R");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });
        jToolBar1.add(jButton11);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        StatusLabel.setText("Status: ");
        getContentPane().add(StatusLabel, java.awt.BorderLayout.PAGE_END);

        buttonGroup1.add(RadioOdstraniPrvega);
        RadioOdstraniPrvega.setText("Odstrani prvega");

        buttonGroup1.add(RadioDodaj);
        RadioDodaj.setText("Dodaj");

        buttonGroup1.add(RadioOdstraniIzbranega);
        RadioOdstraniIzbranega.setText("Odstrani izbranega");
        RadioOdstraniIzbranega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioOdstraniIzbranegaActionPerformed(evt);
            }
        });

        TextVnos.setText("Vnosno polje...");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senožeče" }));

        BtnIzvedi.setText("Izvedi izbrano akcijo");
        BtnIzvedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izvediIzbranoAkcijo(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onSpinnerChange(evt);
            }
        });

        CheckDvojniki.setText("Prepovej dvojnike");
        CheckDvojniki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckDvojnikiActionPerformed(evt);
            }
        });

        izhodLabel.setText("Vrstica za sporočila: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioOdstraniPrvega)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextVnos, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadioDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CheckDvojniki))
                            .addComponent(RadioOdstraniIzbranega))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtnIzvedi))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(izhodLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextVnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioDodaj)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckDvojniki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioOdstraniPrvega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioOdstraniIzbranega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnIzvedi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(izhodLabel)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setMnemonic('D');
        jMenu1.setText("Datoteka");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('O');
        jMenuItem1.setText("Odpri");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpriDatoteko(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setMnemonic('P');
        jMenuItem2.setText("Pobriši");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobrisiIzhode(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setMnemonic('I');
        jMenuItem3.setText("Izhod");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koncajProgram(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('1');
        jMenu2.setText("Izbire1");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusBtn(evt);
            }
        });

        jMenuItem4.setMnemonic('T');
        jMenuItem4.setText("Izbire1 T");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setMnemonic('O');
        jMenuItem5.setText("Izbire1 O");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setMnemonic('M');
        jMenuItem6.setText("Izbire1 M");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setMnemonic('A');
        jMenuItem7.setText("Izbire1 A");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setMnemonic('\u017d');
        jMenuItem8.setText("Izbire1 Ž");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('2');
        jMenu3.setText("Izbire2");

        jMenuItem9.setMnemonic('L');
        jMenuItem9.setText("Izbira2 L");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setMnemonic('U');
        jMenuItem10.setText("Izbira2 U");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setMnemonic('N');
        jMenuItem11.setText("Izbira2 N");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setMnemonic('D');
        jMenuItem12.setText("Izbira2 D");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setMnemonic('E');
        jMenuItem13.setText("Izbira2 E");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setMnemonic('R');
        jMenuItem14.setText("Izbira2 R");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajStatusMenu(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu4.setMnemonic('P');
        jMenu4.setText("Pomoč");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioOdstraniIzbranegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioOdstraniIzbranegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioOdstraniIzbranegaActionPerformed

    private void CheckDvojnikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckDvojnikiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckDvojnikiActionPerformed

    //Doda črko v status v primeru, da je bil pritisnjen gumb v orodni vrstici
    private void dodajStatusBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajStatusBtn
        JButton pressed = (JButton) evt.getSource();
        int mnemonic = pressed.getMnemonic();
        StatusLabel.setText(StatusLabel.getText() + Character.toString((char) mnemonic));     
    }//GEN-LAST:event_dodajStatusBtn

    //Doda črko v status v primeru, da je bil pritisnjen gumb iz menija (Izbira1 oz. Izbira2)
    private void dodajStatusMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajStatusMenu
        JMenuItem pressed = (JMenuItem) evt.getSource();
        int mnemonic = pressed.getMnemonic();
        StatusLabel.setText(StatusLabel.getText() + Character.toString((char) mnemonic));    
    }//GEN-LAST:event_dodajStatusMenu

    private void izvediIzbranoAkcijo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izvediIzbranoAkcijo
        if(RadioDodaj.isSelected()){
            String vnos = TextVnos.getText();
            if(!vnos.equals("")){
                //Če dvojniki niso dovoljeni
                if(CheckDvojniki.isSelected()){
                    int dolzina = jComboBox1.getItemCount();
                    boolean enak = false;
                    for(int i = 0; i < dolzina; i++){
                        if(jComboBox1.getItemAt(i).equals(vnos)){
                            enak = true;
                            izhodLabel.setText(IZHOD_PRE + "Dodajam... NAPAKA: Element že obstaja!");
                            break;
                        }
                    }
                    if(!enak){
                        jComboBox1.addItem(vnos);
                        izhodLabel.setText(IZHOD_PRE + "Dodajam... Uspešno :)");
                    }

                //Če dvojniki so dovoljeni
                } else {
                    jComboBox1.addItem(vnos);
                    izhodLabel.setText(IZHOD_PRE + "Dodajam... Uspešno :)");
                }
            }
        } else if (RadioOdstraniPrvega.isSelected()){
            if(jComboBox1.getItemCount() > 0){
                jComboBox1.removeItemAt(0);
                izhodLabel.setText(IZHOD_PRE + "Odstranjujem prvega... Uspešno :)");
            }
            else {
                izhodLabel.setText(IZHOD_PRE + "Odstranjujem prvega... NAPAKA: Elementa ni!");
            }
        
        } else if (RadioOdstraniIzbranega.isSelected()){
            if(jComboBox1.getItemCount() > 0){
                int izbran = jComboBox1.getSelectedIndex();
                jComboBox1.removeItemAt(izbran);
                izhodLabel.setText(IZHOD_PRE + "Odstranjujem izbrangea... Uspešno :)");
            } else {
                izhodLabel.setText(IZHOD_PRE + "Odstranjujem izbranega... NAPAKA: Elementa ni!");
            }
          
        }
    }//GEN-LAST:event_izvediIzbranoAkcijo

    private void onSpinnerChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onSpinnerChange
        int spinner = (int) jSpinner1.getValue();
        if(jComboBox1.getItemCount() > spinner){
            izhodLabel.setText(IZHOD_PRE + jComboBox1.getItemAt(spinner));
        } else {
            izhodLabel.setText(IZHOD_PRE + "Ni elementa.");
        }
    }//GEN-LAST:event_onSpinnerChange

    private void koncajProgram(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koncajProgram
        System.exit(0);
    }//GEN-LAST:event_koncajProgram

    private void pobrisiIzhode(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobrisiIzhode
        StatusLabel.setText("Status: ");
        izhodLabel.setText(IZHOD_PRE);
    }//GEN-LAST:event_pobrisiIzhode

    private void odpriDatoteko(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpriDatoteko
        int neki = jFileChooser1.showOpenDialog(jPanel1) ;
    }//GEN-LAST:event_odpriDatoteko

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIzvedi;
    private javax.swing.JCheckBox CheckDvojniki;
    private javax.swing.JRadioButton RadioDodaj;
    private javax.swing.JRadioButton RadioOdstraniIzbranega;
    private javax.swing.JRadioButton RadioOdstraniPrvega;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTextField TextVnos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel izhodLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
